name: Deploy to server

on:
  push:
    branches:
    - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    
    runs-on: ubuntu-latest
    steps:
    # Check out
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    # Generate page
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run generate
    # Deploy  
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://suckatcoding.com
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
